#!/bin/bash
# Manual push script generated by Antigravity
# Usage: bash scripts/manual_push.sh

echo "Starting manual push..."
git status
git add .
message="Automated push: Saving all changes $(date)"
echo "Committing with message: $message"
git commit -m "$message"
echo "Pushing to remote..."
git push
echo "Push complete!"
